### ISSUE TITLE
Deleting the last element from specifications crashes the app

### ISSUE THREAD

**Issue by asver12** [lumen-org/LumenReact#66]
When I delete this item: 
![deleting](https://user-images.githubusercontent.com/22447805/102202615-d5b8bc80-3ec7-11eb-84ad-3c19ff91bdb2.png)
this error occurs
![error_deleting_last_spec](https://user-images.githubusercontent.com/22447805/102202646-e1a47e80-3ec7-11eb-8e75-0c0895fe7c00.png)
:

**Comment by laureleya** [comment]
fixed in PR #68
